flyway.url=${env.TM_DB_URL}
flyway.user=${env.TM_DB_USERNAME}
flyway.password=${env.TM_DB_PASSWORD}
flyway.locations=filesystem:src/main/resources/db/migration
flyway.baselineOnMigrate=true
flyway.baselineVersion=0